# Generated by Django 5.2.6 on 2025-10-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Launch',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('links', models.JSONField(blank=True)),
                ('date_unix', models.DateTimeField(blank=True)),
                ('window', models.IntegerField()),
                ('rocket', models.CharField()),
                ('success', models.BooleanField()),
                ('failures', models.JSONField(blank=True)),
                ('details', models.CharField(max_length=1000)),
                ('name', models.CharField()),
                ('cores', models.JSONField()),
            ],
        ),
    ]
