# Generated by Django 5.2.6 on 2025-10-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForSpaceEnthusiasts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='launch',
            name='flight_number',
            field=models.IntegerField(default=0),
        ),
    ]
