# Generated by Django 5.2.6 on 2025-10-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForSpaceEnthusiasts', '0002_launch_flight_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='cores',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='launch',
            name='details',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='launch',
            name='name',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='launch',
            name='rocket',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='launch',
            name='success',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='launch',
            name='window',
            field=models.IntegerField(blank=True),
        ),
    ]
