# Generated by Django 5.2.6 on 2025-10-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForSpaceEnthusiasts', '0003_alter_launch_cores_alter_launch_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='details',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
