# Generated by Django 5.2.6 on 2025-10-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForSpaceEnthusiasts', '0004_alter_launch_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='cores',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='launch',
            name='date_unix',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='launch',
            name='details',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='launch',
            name='failures',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='launch',
            name='links',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='launch',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='launch',
            name='rocket',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='launch',
            name='success',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='launch',
            name='window',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
