# Generated by Django 5.2.6 on 2025-10-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForSpaceEnthusiasts', '0005_alter_launch_cores_alter_launch_date_unix_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('name', models.CharField()),
                ('agency', models.CharField()),
                ('image', models.CharField(blank=True, null=True)),
                ('wikipedia', models.URLField(blank=True, null=True)),
                ('launches', models.JSONField()),
                ('status', models.CharField()),
                ('id', models.CharField(primary_key=True, serialize=False)),
            ],
        ),
    ]
