# Generated by Django 5.2.6 on 2025-10-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForSpaceEnthusiasts', '0006_crew'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('dragon', models.JSONField()),
                ('name', models.CharField()),
                ('type', models.CharField()),
                ('reuse', models.BooleanField()),
                ('launch', models.CharField()),
                ('customers', models.JSONField()),
                ('norad_ids', models.JSONField()),
                ('nationalities', models.JSONField()),
                ('manufacturers', models.JSONField()),
                ('mass_kg', models.FloatField()),
                ('mass_lbs', models.FloatField()),
                ('orbit', models.CharField()),
                ('reference_system', models.CharField()),
                ('regime', models.CharField()),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('semi_major_axis_km', models.FloatField(blank=True, null=True)),
                ('eccentricity', models.FloatField(blank=True, null=True)),
                ('periapsis_km', models.FloatField(blank=True, null=True)),
                ('apoapsis_km', models.FloatField(blank=True, null=True)),
                ('inclination_deg', models.FloatField(blank=True, null=True)),
                ('period_min', models.FloatField(blank=True, null=True)),
                ('lifespan_years', models.FloatField(blank=True, null=True)),
                ('epoch', models.DateTimeField(blank=True, null=True)),
                ('mean_motion', models.FloatField(blank=True, null=True)),
                ('raan', models.FloatField(blank=True, null=True)),
                ('arg_of_pericenter', models.FloatField(blank=True, null=True)),
                ('mean_anomaly', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
