# Generated by Django 5.2.6 on 2025-10-07 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ForSpaceEnthusiasts', '0007_payload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payload',
            old_name='reuse',
            new_name='reused',
        ),
    ]
