# Generated by Django 5.2.6 on 2025-10-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForSpaceEnthusiasts', '0008_rename_reuse_payload_reused'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payload',
            name='mass_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payload',
            name='mass_lbs',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
