# Generated by Django 5.2.6 on 2025-10-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForSpaceEnthusiasts', '0009_alter_payload_mass_kg_alter_payload_mass_lbs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payload',
            name='regime',
            field=models.CharField(blank=True, null=True),
        ),
    ]
