# Generated by Django 5.2.6 on 2025-10-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForSpaceEnthusiasts', '0010_alter_payload_regime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payload',
            name='reference_system',
            field=models.CharField(blank=True, null=True),
        ),
    ]
