# Generated by Django 5.2.6 on 2025-10-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForSpaceEnthusiasts', '0011_alter_payload_reference_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payload',
            name='orbit',
            field=models.CharField(blank=True, null=True),
        ),
    ]
