# Generated by Django 5.2.6 on 2025-10-08 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForSpaceEnthusiasts', '0013_alter_crew_image_alter_crew_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='date_unix',
            field=models.DateTimeField(),
        ),
    ]
