# Generated by Django 5.2.6 on 2025-10-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForSpaceEnthusiasts', '0014_alter_launch_date_unix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crew',
            name='launches',
        ),
        migrations.AddField(
            model_name='crew',
            name='flights',
            field=models.ManyToManyField(to='ForSpaceEnthusiasts.launch'),
        ),
        migrations.AddField(
            model_name='launch',
            name='crew_members',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='launch',
            name='flight_number',
            field=models.IntegerField(),
        ),
    ]
