# Generated by Django 5.2.6 on 2025-10-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForSpaceEnthusiasts', '0015_remove_crew_launches_crew_flights_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payload',
            old_name='launch',
            new_name='launches',
        ),
        migrations.AddField(
            model_name='launch',
            name='payloads',
            field=models.ManyToManyField(to='ForSpaceEnthusiasts.payload'),
        ),
    ]
