# Generated by Django 5.2.6 on 2025-10-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForSpaceEnthusiasts', '0016_rename_launch_payload_launches_launch_payloads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payload',
            name='launches',
            field=models.JSONField(),
        ),
    ]
