# Generated by Django 5.2.6 on 2025-10-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForSpaceEnthusiasts', '0017_alter_payload_launches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payload',
            name='launches',
            field=models.JSONField(null=True),
        ),
    ]
