# Generated by Django 5.2.6 on 2025-10-09 01:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForSpaceEnthusiasts', '0018_alter_payload_launches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='launch',
            name='payloads',
        ),
        migrations.RemoveField(
            model_name='payload',
            name='launches',
        ),
        migrations.AddField(
            model_name='payload',
            name='launch',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='ForSpaceEnthusiasts.launch'),
            preserve_default=False,
        ),
    ]
