# Generated by Django 5.2.6 on 2025-10-09 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForSpaceEnthusiasts', '0019_remove_launch_payloads_remove_payload_launches_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payload',
            name='launch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payload', to='ForSpaceEnthusiasts.launch'),
        ),
    ]
